# Configuração do Dependabot para atualizações automáticas de dependências
# Mais informações: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # Dependências do npm (React Native)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "rafaelminatto1"
    assignees:
      - "rafaelminatto1"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    ignore:
      # Ignorar atualizações major de algumas dependências críticas
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@react-native-community/*"
        update-types: ["version-update:semver-major"]

  # Dependências do backend (se houver package.json separado)
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rafaelminatto1"
    assignees:
      - "rafaelminatto1"
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "npm"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rafaelminatto1"
    assignees:
      - "rafaelminatto1"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"

  # Docker (se houver Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "rafaelminatto1"
    assignees:
      - "rafaelminatto1"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"